# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for JaxBot Console executable

a = Analysis(
    ['jaxbot_console.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('nano.env', '.'),
        ('config.yaml', '.'),
        ('low_resource_config.yaml', '.'),
    ],
    hiddenimports=[
        'vrchatapi',
        'vrchatapi.api',
        'vrchatapi.api.authentication_api',
        'vrchatapi.api.friends_api',
        'vrchatapi.exceptions',
        'vrchatapi.models',
        'vrchatapi.models.two_factor_auth_code',
        'vrchatapi.models.two_factor_email_code',
        'yaml',
        'dotenv',
        'psutil',
        'pythonosc',
        'pythonosc.udp_client',
        'pyttsx3',
        'pyttsx3.drivers',
        'pyttsx3.drivers.espeak',
        'pyttsx3.drivers.sapi5',
        'pyttsx3.drivers.nsss',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'PIL',
        'cv2',
        'torch',
        'tensorflow',
        'tkinter',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='JaxBot',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
